apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "flink-sessioncluster.fullname" . }}-taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "flink-sessioncluster.fullname" . }}
        component: taskmanager
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: taskmanager
        image: "{{ .Values.taskmanager.image.repository }}:{{ .Values.taskmanager.image.tag }}"
        imagePullPolicy: {{ .Values.taskmanager.image.pullPolicy }}
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/taskmanager.sh start; \
          while :;
          do
            if [[ -f $(find log -name '*taskmanager*.log' -print -quit) ]];
              then tail -f -n +1 log/*taskmanager*.log;
            fi;
          done"]
        ports:
        - containerPort: 6122
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: hadoop-config-volume
          mountPath: /usr/local/hadoop/etc/hadoop
      volumes:
      - name: flink-config-volume
        configMap:
          name: {{ include "flink-sessioncluster.fullname" . }}-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
      - name: hadoop-config-volume
        configMap:
          name: {{ include "flink-sessioncluster.fullname" . }}-hdfs-config
          items:
          - key: core-site.xml
            path: core-site.xml