apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink-sessioncluster.fullname" . }}-jobmanager-rest
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: {{ include "flink-sessioncluster.fullname" . }}
    component: jobmanager