apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink-sessioncluster.fullname" . }}-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: ui
    port: 8081
  selector:
    app: {{ include "flink-sessioncluster.fullname" . }}
    component: jobmanager